# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gorg's Blog
#email: schore.r@gmx.de
description: >- # this means to ignore newlines until "baseurl:"
   Dies ist ein kleiner privater Blog der akuelle Gedanken zum Tag, aktuelle
   Trends über Linux, Programmieren und vieles mehr zu finden ist.
  
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://schore.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

default:
  -scope:
    path: "asset"
    values:
      image: true

keywords: "Linux,Emacs,Gorg,Gorg's,Software,Coding,Code"
